{% set name = "batman-package" %}
{% set version = "2.4.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7ebc7e83e60473801068ea726532f0b6403e584ec1f96b0310e91f5554d05b1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy >1.11
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - batman

about:
  home: https://github.com/lkreidberg/batman
  summary: Fast transit light curve modeling
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  description: |
    The batman package supports calculation of light curves for any radially
    symmetric stellar limb darkening law, using a new integration algorithm
    for models that cannot be quickly calculated analytically.
  doc_url: https://www.cfa.harvard.edu/~lkreidberg/batman/
  dev_url: https://github.com/lkreidberg/batman

extra:
  recipe-maintainers:
    - mwcraig
