{% set name = "batman-package" %}
{% set version = "2.4.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bcb88925692ccce0bcf1f8775963971f5cf29848f8498bdc47bf1ae6de0fb08e
  patches:
    # Patch from upstream to avoid distutils to be released in 2.5.0
    - setup.py.patch  # {py>=312}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - batman

about:
  home: https://github.com/lkreidberg/batman
  summary: Fast transit light curve modeling
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  description: |
    The batman package supports calculation of light curves for any radially
    symmetric stellar limb darkening law, using a new integration algorithm
    for models that cannot be quickly calculated analytically.
  doc_url: https://www.cfa.harvard.edu/~lkreidberg/batman/
  dev_url: https://github.com/lkreidberg/batman

extra:
  recipe-maintainers:
    - mwcraig
